# Generated by Django 5.2.6 on 2025-12-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserLogic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('duration', models.PositiveIntegerField()),
                ('photo', models.FileField(upload_to='Photo/Track')),
                ('postDate', models.DateField()),
                ('genre', models.CharField(max_length=40)),
                ('path', models.FileField(upload_to='Songs/<django.db.models.fields.CharField>')),
                ('likes', models.PositiveIntegerField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogic.author')),
            ],
        ),
    ]
