# Generated by Django 5.2.6 on 2026-01-08 09:12

import TrackLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackLogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.FileField(upload_to=TrackLogic.models.track_file_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.FileField(upload_to=TrackLogic.models.track_photo_path),
        ),
    ]
