# Generated by Django 5.2.6 on 2026-01-21 17:24

import TrackLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackLogic', '0002_alter_track_path_alter_track_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.ImageField(upload_to=TrackLogic.models.track_photo_path),
        ),
    ]
