# Generated by Django 5.2.6 on 2025-12-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TrackLogic', '0001_initial'),
        ('UserLogic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('number_of_track', models.PositiveIntegerField()),
                ('createDate', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogic.clients')),
                ('tracks', models.ManyToManyField(to='TrackLogic.track')),
            ],
        ),
    ]
