# Generated by Django 5.2.6 on 2026-01-08 09:12

import PlayListsLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListsLogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='photo',
            field=models.FileField(default=1, upload_to=PlayListsLogic.models.playlist_photo_path),
            preserve_default=False,
        ),
    ]
