# Generated by Django 5.2.6 on 2026-01-21 17:24

import PlayListsLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListsLogic', '0002_playlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(upload_to=PlayListsLogic.models.playlist_photo_path),
        ),
    ]
