# Generated by Django 5.2.6 on 2026-01-08 09:12

import UserLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.FileField(upload_to=UserLogic.models.users_photo_path),
        ),
    ]
