# Generated by Django 5.2.6 on 2026-01-21 17:24

import UserLogic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogic', '0002_alter_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(upload_to=UserLogic.models.users_photo_path),
        ),
    ]
